version: "3.3"

services:
  snikket_proxy:
    container_name: snikket-proxy
    image: snikket/snikket-web-proxy:beta
    env_file: snikket.conf
    network_mode: host
    volumes:
      - snikket_data:/snikket
      - acme_challenges:/var/www/html/.well-known/acme-challenge
      - ./branding/assets/most-logo.svg:/var/www/html/static/img/snikket-logo-text.svg:ro
      - ./branding/assets/most-logo.svg:/var/www/html/static/img/snikket-logo.svg:ro
      - ./branding/proxy/startup.html:/var/www/html/index.html:ro
      - ./branding/proxy/error-pages:/var/www/html/_errors:ro
    restart: "unless-stopped"
  snikket_certs:
    container_name: snikket-certs
    image: snikket/snikket-cert-manager:beta
    env_file: snikket.conf
    network_mode: host
    volumes:
      - snikket_data:/snikket
      - acme_challenges:/var/www/.well-known/acme-challenge
    restart: "unless-stopped"
  snikket_portal:
    container_name: snikket-portal
    image: snikket/snikket-web-portal:beta
    network_mode: host
    env_file: snikket.conf
    depends_on:
      snikket_server:
        condition: service_healthy
    volumes:
      - ./branding/assets/most-logo.svg:/opt/snikket-web-portal/snikket_web/static/img/snikket-logo.svg:ro
      - ./branding/assets/most-logo.svg:/opt/snikket-web-portal/snikket_web/static/img/snikket-logo-text.svg:ro
      - ./branding/portal/templates/_footer.html:/opt/snikket-web-portal/snikket_web/templates/_footer.html:ro
      - ./branding/portal/templates/base.html:/opt/snikket-web-portal/snikket_web/templates/base.html:ro
    restart: "unless-stopped"

  snikket_server:
    container_name: snikket
    image: snikket/snikket-server:beta
    network_mode: host
    volumes:
      - snikket_data:/snikket
    env_file: snikket.conf
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:5280/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    restart: "unless-stopped"

volumes:
  acme_challenges:
  snikket_data:
